# Generated by Django 3.0.5 on 2021-05-02 04:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Quiz_App', '0003_formtitle_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=jsonfield.fields.JSONField(max_length=200),
        ),
    ]
